version: '3'

volumes:
  seance-db-data:
    external: true

services:
  db:
    image: postgres:11-alpine
    environment:
      PGHOST: db
      POSTGRES_PASSWORD: postgres
    volumes:
      - seance-db-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - seance-db-data:/var/lib/postgresql/data
    stdin_open: true
    tty: true
    environment:
      - PGDATABASE
      - PGHOST
      - PGPASSWORD
      - PGPORT
      - PGUSER
      - SIGNING_SECRET
    ports:
      - "4000:4000"
    links:
      - db
    command:
      - ./bin/run.sh
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:
        - ./bin/test.sh
    volumes:
      - .:/app
      - seance-db-data:/var/lib/postgresql/data
    links:
      - db
    environment:
      - PGDATABASE=seance_test
      - PGHOST
      - PGPORT
      - PGUSER
      - SIGNING_SECRET
  release:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PGDATABASE
      - PGHOST
      - PGPASSWORD
      - PGPORT
      - PGUSER
      - SIGNING_SECRET
    ports:
      - "4000:4000"
